elearning/apps/courseapp/urls.py
from django.urls import path
from apps.courseapp import views

# Create your views here.
app_name = "courseapp"
urlpatterns = [
    path('',views.index, name="course_url"),
    path('delete_course/<int:course_id>/', views.DeleteCourse,name="delete_url"),
    path('course_info/',views.CourseInfo, name="courseInfo_url"),
    path('addmodule/<int:id>/',views.AddModule,name="AddModule_url"),
    path('deletemodule/<int:id>/',views.deleteModule, name="DelModule_url"),
    path('deletelesson/<int:id>/',views.deleteLesson, name="DelLesson_url"),
]

elearning/apps/instructorapp/urls.py
from django.urls import path
from apps.instructorapp import views

app_name = "instructorapp"
urlpatterns = [
    path('',views.dashboard, name="instructor_dashboard"),
    path('addcourse/', views.AddCourse, name="instructo_addcourse"),
    path('editcourse/<int:id>/',views.EditCourse, name="edit_url")
]

elearning/elearning/urls.py
from django.conf import settings
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path, re_path
from apps.accountapp import urls as account_url
from apps.profileapp import urls as profile_url
from apps.courseapp import urls as course_url
from apps.instructorapp import urls as instructor_url
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.views.static import serve 

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    path('admin/', admin.site.urls),
    path('', lambda request: render(request, 'base.html'), name='empty_url'),
    path("__reload__/", include("django_browser_reload.urls")),
    path('account/', include(account_url)),
    path('profile/', include(profile_url)),
    path('course/', include(course_url)),
    path('instructor/', include(instructor_url))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elearning/apps/instructorapp/models.py
from django.db import models

# Create your models here.

elearning/apps/instructorapp/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget

class CourseForm(forms.Form):
    title = forms.CharField(
        label="Course Title",
        max_length=150,
        widget=forms.TextInput(attrs={
            'placeholder':'Enter course title',
            "class":'w-full border border-border rounded-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary mb-2'
        })
    )
    
    description = forms.CharField(
        label="Description",
        widget=forms.Textarea(attrs={
            'placeholder':'Provide more detail description about this course',
            "class":'w-full border border-border rounded-md resize-none h-64 focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary mb-2',
        })
    )
    course_img = forms.ImageField(
        label="Course Logo",
        widget=forms.ClearableFileInput())
    
    certificate = forms.ImageField(
        label="Certificate (Image format)",
        widget=forms.ClearableFileInput())
    
    
class ModuleForm(forms.Form):
    title = forms.CharField(
        max_length=150,
        label="Module Title",
        widget=forms.TextInput(attrs={
            'placeholder':'Enter module title',
            'class':'w-full border border-border rounded-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary mb-2'
        })
    )
    
    description = forms.CharField(
        label="Description",
        widget=forms.Textarea(attrs={
            'placeholder':'Enter description for this module',
            'class':'w-full border border-border rounded-md resize-none h-64 focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary mb-2'
        })
    )
    
    cover_img = forms.ImageField(
        widget=forms.ClearableFileInput(),
        required=False)
    
    
class LessonForm(forms.Form):
    
    module = forms.CharField(
        widget=forms.TextInput(attrs={
        'id':'module_id',
        'type':'hidden'
    })
    )
    title = forms.CharField(
        max_length=150,
        label="Lesson Title",
        widget=forms.TextInput(attrs={
            'placeholder':'Enter Lesson title',
            'class':'w-full border border-border rounded-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary mb-2'
        })
    )
    content = forms.CharField(widget=CKEditorWidget())
    cover_img = forms.ImageField(
        widget=forms.ClearableFileInput(),
        required=False
    )

elearning/apps/instructorapp/views.py
from django.shortcuts import redirect, render, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import *
from ..accountapp.models import Instructor
from ..courseapp.models import *
# Create your views here.
@login_required(login_url='/account/') #get back to login
def dashboard(request):
    
    is_instructor = request.user.is_instructor
    
    if not is_instructor:
        #redirect to login and decide whether it should be on homepage or should log in first
        return redirect('accountapp:login_url')
    else: 
        # go to dashboard page
        course_form = CourseForm()
        instructor = Instructor.objects.get(user=request.user)
        templates = "dashboard.html"
        courses = GetCourses(instructor)
        full_name = f"{request.user.first_name} {request.user.last_name}"
        context = {
            "courses":courses,
            "instructor":full_name,
            "forms":course_form,
        }

        return render(request,templates,context)
    
# ------------ Display courses -----------------   
def GetCourses(instructor):
    course_obj = Course.objects.filter(instructor=instructor)

    course_data = []

    for course in course_obj:
        course_info = {
            "ID":course.id,
            "Title": course.title,
            "Description": course.description,
            "Image": course.course_img,
            "Published_date": course.formatted_date(),
            "Module_count":course.count_modules,
            "Student_count":course.count_enrolled,
        }
        course_data.append(course_info)

    return course_data


# ------------ Create new course ---------------
login_required(login_url="/account/")
def AddCourse(request):
    if request.method == "POST":
        try:
            form = CourseForm(request.POST, request.FILES)
            if form.is_valid():
                
                 # add new course data
                instructor = Instructor.objects.get(user = request.user)
                title = form.cleaned_data['title']
                description = form.cleaned_data['description']
                course_img = form.cleaned_data['course_img']
                certificate = form.cleaned_data['certificate']
                
                course_obj = Course(instructor = instructor,
                                title = title,
                                description=description, 
                                course_img = course_img,
                                certificate = certificate)

                course_obj.save()
                messages.success(request,"Success: New course added.")
            else:
                messages.error(request, f"Error: {form.errors}")
        except Exception as e:
            messages.error(request, f"Error: {e}")
            
    #back to previous page
    previous_page = request.META.get('HTTP_REFERER')
    return redirect(previous_page)




# ------------- edit course ---------------------
login_required(login_url="/account/")
def EditCourse(request,id):
    templates = "editcourse.html"

    #starting data
    course_obj = Course.objects.get(id=id)
    add_lesson_form = LessonForm()
    add_module_form = ModuleForm()
    context = {
        "course_obj":course_obj,
        "course_id":id,
        "title":course_obj.title,
        "module_form":add_module_form,
        "lesson_form":add_lesson_form,
    }
    
    return render(request, templates, context)

elearning/apps/instructorapp/templates/createnewcourse.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
    Add Course
{% endblock %}

{% block content %}
    <div class="h-full">
        {% include 'course_content/sidebar.html' %}
    </div>
{% endblock %}

elearning/apps/instructorapp/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Dashboard
{% endblock %}

{% block content %}
    <div class="overflow-y-auto p-5">
        <h2 class="text-lg md:text-4xl font-bold text-secondary-0">Your Courses</h2>
        <div class="grid grid-cols-2 md:grid-cols-3 gap-5 p-8">
            <!-- create new course button -->
            <div id="new-course-btn" class="h-full w-full p-5 bg-primary hover:bg-accent-g rounded-md flex flex-col items-center gap-3 cursor-pointer justify-center"
                onclick="NewCourseModal('open')">
                <i class="fa-solid fa-square-plus text-white text-3xl md:text-6xl"></i>
                <span class="text-sm text-center md:text-2xl text-white font-bold">Create New Course</span>
            </div>

            {% comment %} Display all the courses made by this current instructor {% endcomment %}
            {% for course in courses %}
                <div class="h-full w-full rounded-md flex flex-col items-center cursor-pointer justify-center shadow-sm shadow-gray-400">
                    <div class="h-14 w-full rounded-t-md py-16 bg-accent-g relative">
                        <i class="fa-solid fa-ellipsis absolute top-2 right-4 text-secondary-0" onclick="openDelete(this)"></i>

                        <!-- delete course -->
                        <form id="delete_course_form" method="post" action="{% url 'courseapp:delete_url' course.ID %}" class="absolute top-5 right-3 hidden delButton">
                            {% csrf_token %}
                            <button type="submit" class="bg-white px-3 py-1 text-sm rounded-md text-gray-500 hover:bg-slate-300" onclick="deleteCourse()">Delete</button>
                        </form>
                    </div>
                    <div class="h-full w-full p-3 gap-2 flex flex-col justify-center md:flex-row">
                        <div class="w-max h-full">
                            <img src="{{ course.Image.url }}" class="h-12 w-12 border object-contain border-secondary-0 rounded-full" alt="">
                        </div>
                        
                        <div class="flex flex-col w-4/5">
                            {% comment %} Course title {% endcomment %}
                            <div class="flex md:flex-row gap-2 items-center">
                                <p class="font-medium text-lg">{{ course.Title }}</p>
                                <span class="bg-primary text-white rounded-full px-2 py-1 text-sm">{{ course.Module_count }} Modules</span>
                            </div>
                            
                            {% comment %} author {% endcomment %}
                            <span class="text-gray-700 font-medium">By: {{ instructor }}</span>
                            {% comment %} description with 15 character {% endcomment %}
                            <p class="text-sm">{{ course.Description|slice:":150" }}</p>
                            
                        </div>

                        
                    </div>


                    <div class="flex flex-wrap gap-2 w-full justify-between px-3 mb-2">
                        <div class="flex gap-1 items-center">
                            <!-- date posted -->
                            <span class="px-3 py-1 rounded-full bg-accent-g font-bold text-xs text-primary">
                                <i class="fa-regular fa-calendar"></i>
                                {{ course.Published_date }}
                            </span>

                            <!-- number of students -->
                            <span class="px-3 py-1 rounded-full bg-accent-0 text-secondary-0 font-bold text-xs">
                                <i class="fa-regular fa-calendar"></i>
                                {{ course.Student_count }} Students

                            </span>
                        </div>
                        
                        <a href="{% url 'instructorapp:edit_url' id=course.ID %}" class="px-3 py-2 rounded-full bg-secondary-v text-white text-xs font-semibold">View course</a>
                    </div>

                </div>
            {% endfor %}    
            
        </div>

        <!-- add new course modal -->
        <div id="create-course-modal" class="modal w-full h-full absolute top-0 left-0 bg-black bg-opacity-50 flex items-center justify-center hidden">
            <form method="post" action="{% url 'instructorapp:instructo_addcourse' %}" enctype="multipart/form-data" class="w-2/5 bg-white rounded-md p-5 text-gray-700">
                {% csrf_token %}
                <h2 class="text-center text-2xl text-secondary-0 font-bold mb-5">New Course</h2>

                {{ forms.title.label }}
                {{ forms.title }}
                
                {{ forms.description.label }}
                {{ forms.description }}
                
                <div class="flex md:flex-row flex-col">
                    <div class="flex flex-col w-1/2">
                        {{ forms.course_img.label }}
                        {{ forms.course_img }}
                    </div>
                    <div class="flex flex-col w-1/2">
                        {{ forms.certificate.label }}
                        {{ forms.certificate }}
                    </div>
                    
                </div>
                
                <button type="submit" class="w-full bg-primary text-white font-medium rounded-md mt-5 py-2 hover:bg-dark-green">Create course</button>
                <button type="button" class="text-gray-500 w-full hover:bg-gray-300 mt-1" onclick="NewCourseModal('close')">Cancel</button>
            </form>
        </div>
    </div>
    
    <script src="{% static 'js/instructor.js' %}"></script>
{% endblock %}

elearning/apps/instructorapp/templates/editcourse.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
    Add Course
{% endblock %}

{% block content %}
    <div class="h-full p-5 flex gap-2">
        
        {% include 'edit_page_content/sidebar.html' %}
        <div id="lesson_view" class="w-full h-full overflow-y-auto">
            View
        </div>
        <div id="add_lesson_view" class="w-full h-full overflow-y-auto hidden">
            {% include 'edit_page_content/addlesson.html' %}
        </div>
        
        
    </div>
{% endblock %}