elearning/apps/courseapp/urls.py
from django.urls import path
from apps.courseapp import views

# Create your views here.
app_name = "courseapp"
urlpatterns = [
    path('',views.index, name="course_url"),
    path('delete_course/<int:course_id>/', views.DeleteCourse,name="delete_url"),
    path('course_info/',views.CourseInfo, name="courseInfo_url"),
    path('addmodule/<int:id>/',views.AddModule,name="AddModule_url"),
    path('deletemodule/<int:id>/',views.deleteModule, name="DelModule_url"),
    path('deletelesson/<int:id>/',views.deleteLesson, name="DelLesson_url"),
]

elearning/apps/instructorapp/urls.py
from django.urls import path
from apps.instructorapp import views

app_name = "instructorapp"
urlpatterns = [
    path('',views.dashboard, name="instructor_dashboard"),
    path('addcourse/', views.AddCourse, name="instructo_addcourse"),
    path('editcourse/<int:id>/',views.EditCourse, name="edit_url")
]

elearning/elearning/urls.py
from django.conf import settings
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path, re_path
from apps.accountapp import urls as account_url
from apps.profileapp import urls as profile_url
from apps.courseapp import urls as course_url
from apps.instructorapp import urls as instructor_url
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.views.static import serve 

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    path('admin/', admin.site.urls),
    path('', lambda request: render(request, 'base.html'), name='empty_url'),
    path("__reload__/", include("django_browser_reload.urls")),
    path('account/', include(account_url)),
    path('profile/', include(profile_url)),
    path('course/', include(course_url)),
    path('instructor/', include(instructor_url))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elearning/apps/instructorapp/models.py
from django.db import models

# Create your models here.

elearning/apps/instructorapp/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget

class CourseForm(forms.Form):
    title = forms.CharField(
        label="Course Title",
        max_length=150,
        widget=forms.TextInput(attrs={
            'placeholder':'Enter course title',
            "class":'w-full border border-border rounded-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary mb-2'
        })
    )
    
    description = forms.CharField(
        label="Description",
        widget=forms.Textarea(attrs={
            'placeholder':'Provide more detail description about this course',
            "class":'w-full border border-border rounded-md resize-none h-64 focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary mb-2',
        })
    )
    course_img = forms.ImageField(
        label="Course Logo",
        widget=forms.ClearableFileInput())
    
    certificate = forms.ImageField(
        label="Certificate (Image format)",
        widget=forms.ClearableFileInput())
    
    
class ModuleForm(forms.Form):
    title = forms.CharField(
        max_length=150,
        label="Module Title",
        widget=forms.TextInput(attrs={
            'placeholder':'Enter module title',
            'class':'w-full border border-border rounded-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary mb-2'
        })
    )
    
    description = forms.CharField(
        label="Description",
        widget=forms.Textarea(attrs={
            'placeholder':'Enter description for this module',
            'class':'w-full border border-border rounded-md resize-none h-64 focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary mb-2'
        })
    )
    
    cover_img = forms.ImageField(
        widget=forms.ClearableFileInput(),
        required=False)
    
    
class LessonForm(forms.Form):
    
    module = forms.CharField(
        widget=forms.TextInput(attrs={
        'id':'module_id',
        'type':'hidden'
    })
    )
    title = forms.CharField(
        max_length=150,
        label="Lesson Title",
        widget=forms.TextInput(attrs={
            'placeholder':'Enter Lesson title',
            'class':'w-full border border-border rounded-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary mb-2'
        })
    )
    content = forms.CharField(widget=CKEditorWidget())
    cover_img = forms.ImageField(
        widget=forms.ClearableFileInput(),
        required=False
    )

elearning/apps/instructorapp/views.py
from django.shortcuts import redirect, render, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import *
from ..accountapp.models import Instructor
from ..courseapp.models import *
# Create your views here.
@login_required(login_url='/account/') #get back to login
def dashboard(request):
    
    is_instructor = request.user.is_instructor
    
    if not is_instructor:
        #redirect to login and decide whether it should be on homepage or should log in first
        return redirect('accountapp:login_url')
    else: 
        # go to dashboard page
        course_form = CourseForm()
        instructor = Instructor.objects.get(user=request.user)
        templates = "dashboard.html"
        courses = GetCourses(instructor)
        full_name = f"{request.user.first_name} {request.user.last_name}"
        context = {
            "courses":courses,
            "instructor":full_name,
            "forms":course_form,
        }

        return render(request,templates,context)
    
# ------------ Display courses -----------------   
def GetCourses(instructor):
    course_obj = Course.objects.filter(instructor=instructor)

    course_data = []

    for course in course_obj:
        course_info = {
            "ID":course.id,
            "Title": course.title,
            "Description": course.description,
            "Image": course.course_img,
            "Published_date": course.formatted_date(),
            "Module_count":course.count_modules,
            "Student_count":course.count_enrolled,
        }
        course_data.append(course_info)

    return course_data


# ------------ Create new course ---------------
login_required(login_url="/account/")
def AddCourse(request):
    if request.method == "POST":
        try:
            form = CourseForm(request.POST, request.FILES)
            if form.is_valid():
                
                 # add new course data
                instructor = Instructor.objects.get(user = request.user)
                title = form.cleaned_data['title']
                description = form.cleaned_data['description']
                course_img = form.cleaned_data['course_img']
                certificate = form.cleaned_data['certificate']
                
                course_obj = Course(instructor = instructor,
                                title = title,
                                description=description, 
                                course_img = course_img,
                                certificate = certificate)

                course_obj.save()
                messages.success(request,"Success: New course added.")
            else:
                messages.error(request, f"Error: {form.errors}")
        except Exception as e:
            messages.error(request, f"Error: {e}")
            
    #back to previous page
    previous_page = request.META.get('HTTP_REFERER')
    return redirect(previous_page)




# ------------- edit course ---------------------
login_required(login_url="/account/")
def EditCourse(request,id):
    templates = "editcourse.html"

    #starting data
    course_obj = Course.objects.get(id=id)
    add_lesson_form = LessonForm()
    add_module_form = ModuleForm()
    context = {
        "course_obj":course_obj,
        "course_id":id,
        "title":course_obj.title,
        "module_form":add_module_form,
        "lesson_form":add_lesson_form,
    }
    
    return render(request, templates, context)

elearning/apps/instructorapp/templates/edit_page_content/addlesson.html
{% load static %}
<div class="w-full h-full p-5">
    <form method="POST">
        {{ lesson_form.media }}
        {% csrf_token %}
        {{ lesson_form.as_p }}
        <button type="submit" class="px-3 py-2 rounded-md bg-primary hover:bg-dark-green mt-4 text-white">Add Lesson</button>
        <button type="button" onclick="toggleLessonView()">Cancel</button>
    </form>

</div>

<script src="{% static '/js/instructor.js' %}"></script>

elearning/apps/instructorapp/templates/edit_page_content/sidebar.html
{% load instructortag %}
{% load static %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
<div class="h-full w-1/4 flex md:flex-row">
    <aside class="w-full h-full border-r border-gray-400 flex flex-col gap-2 p-5">
        <!-- course name -->
        <h2 class="font-bold text-secondary-0 text-xl">Course</h2>
        <p type="text" class="rounded-md border border-border" >{{ title }}</p>

        <!-- units -->
        <h2 class="font-bold text-secondary-0 text-xl mt-5">Module</h2>
        <div class="h-full overflow-y-auto  relative">

            <div id="accordion" class="h-[90%] p-2 overflow-y-auto">
                {% RetrieveCourseModule course_obj as modules %}
                
                {% comment %} display all module name {% endcomment %}
                {% for k,v in modules.items %}
                   
                    <h3>
                        {{ k|title }}
                        <i class="fa-regular fa-trash-can text-gray-300 hover:text-red-400" onclick="deleteModuleData('{{ v.id }}',true)"></i>
                        <form id="deleteModalForm_{{ v.id }}" action="{% url 'courseapp:DelModule_url' v.id  %}" method="get" class="hidden"></form>
                    </h3>
                    <div>
                        <ul class="flex flex-col gap-2 cursor-pointer">
                            {% ModuleLesson v as lessons %}
                            {% comment %} display all lesson in every module {% endcomment %}
                            {% for i,j in lessons.items %}
                                <li class="list-disc flex justify-between items-center rounded-sm hover:bg-secondary-0 hover:text-white hover:bg-opacity-50 p-2">
                                    <span>{{j}}</span>
                                    <i class="fa-regular fa-trash-can text-gray-300 hover:text-red-400" onclick="deleteModuleData('{{i}}',false)"></i>
                                    <form id="delLesson_{{i}}" action="{% url 'courseapp:DelLesson_url' i %}" method="get" class="hidden"></form>
                                </li>
                            {% endfor %}
                        </ul>
                        <p class="text-primary text-xs font-bold text-center hover:bg-accent-g bg-opacity-20 py-2 cursor-pointer" onclick="toggleLessonView('{{v.id}}')">
                            <i class="fa-solid fa-plus"></i>
                            Add Lesson
                        </p>
                    </div>
                {% endfor %}
            </div>
            <!-- add new module -->
            <div class="flex justify-center absolute bottom-0 w-full">
                <button type="submit" class="flex items-center gap-2 font-bold text-sm text-primary border border-border p-2 rounded-md
                hover:bg-primary hover:text-white" onclick="NewCourseModal('open')">
                    <i class="fa-solid fa-plus"></i>
                    Add Module
                </button>
                
            </div>
            
        </div>
    </aside>
</div>

<!-- add module modal -->
<div class="absolute top-0 left-0 h-full w-full bg-black bg-opacity-50 flex items-center justify-center modal hidden">
    <div class="w-2/5 h-max bg-white rounded-md p-5">
        <h2 class="text-2xl text-primary font-semibold text-center py-2 border-b border-gray-200">Add Module</h2>
        <form action="{% url 'courseapp:AddModule_url' course_id %}" class="p-2" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <label for="{{ module_form.title.id_for_label }}">Module Title</label>
            {{ module_form.title }}

            <label for="{{ module_form.description.id_for_label }}">Description</label>
            {{ module_form.description }}

            <label for="{{ module_form.cover_img.id_for_label }}">Module cover photo (optional)</label>
            {{ module_form.cover_img }}

            <div class="flex justify-end gap-2">
                <button type="button" class="text-gray-400 hover:bg-gray-300 rounded-md px-4 py-2" onclick="NewCourseModal('close')">Cancel</button>
                <button type="submit" class="bg-primary px-4 py-2 text-white font-semibold hover:bg-dark-green rounded-md">Add</button>
            </div>
        </form>
    </div>
</div>


<script src="{% static 'js/instructor.js' %}"></script>