elearning/apps/accountapp/urls.py
from django.urls import path
from apps.accountapp import views

app_name = "accountapp"
urlpatterns = [
    path('',views.login_user,name="login_url"),
    path('registration/',views.registration, name="register_url"),
]

elearning/elearning/urls.py
from django.conf import settings
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path, re_path
from apps.accountapp import urls as account_url
from apps.profileapp import urls as profile_url
from apps.courseapp import urls as course_url
from apps.instructorapp import urls as instructor_url
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.views.static import serve 

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    path('admin/', admin.site.urls),
    path('', lambda request: render(request, 'base.html'), name='empty_url'),
    path("__reload__/", include("django_browser_reload.urls")),
    path('account/', include(account_url)),
    path('profile/', include(profile_url)),
    path('course/', include(course_url)),
    path('instructor/', include(instructor_url))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elearning/apps/accountapp/models.py
import random
import string
from arrow import now
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    #additional fields for user
    is_instructor = models.BooleanField(default=False)
    
    
class Instructor(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    instructor_description = models.TextField(blank=True, default='')
    profile_img = models.ImageField(null=True, blank=True, upload_to="images/") #default image location
    
    def count_courses(self):
        return self.course_set.count()
    
class Student(models.Model):
    #get random characters
    def RandomStudentNo():
        CHARACTER_LENGTH = 25
        letters = string.ascii_uppercase
        result_str = ''.join(random.choice(letters) for i in range(CHARACTER_LENGTH))
        return result_str
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    #set up new primary key
    student_no_value = f"{RandomStudentNo()}{random.randint(0,1000)}"
    student_no = models.CharField(max_length = 30, primary_key=True, default=student_no_value)
    
    
class Badge(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    badge_name = models.CharField(max_length = 60)
    date_obtain = models.DateTimeField(auto_now = True)
    
    

elearning/apps/accountapp/forms.py
from django import forms
from .models import User
import re
class LoginForm(forms.Form):
    username = forms.CharField(
        label="Email address/username",
        max_length=150,
        widget=forms.TextInput(attrs={
            "placeholder": 'Enter your email/username here...',
            "class": 'w-full rounded-md border border-border py-3 focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary',
        })
    )
    
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={
            "placeholder": 'Enter your password here...',
            "class": 'w-full rounded-md border border-border py-3 focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary',
        })
    )

class RegistrationForm(forms.Form):
    first_name = forms.CharField(
        label="First name",
        max_length=80,
        widget=forms.TextInput(attrs={
            'placeholder':'Enter first name',
            'class':'w-full rounded-md border border-border py-3 focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary',
            'autocomplete':'off'
        })
    )
    last_name = forms.CharField(
        label="Last name",
        max_length=80,
        widget=forms.TextInput(attrs={
            'placeholder':'Enter last name',
            'class':'w-full rounded-md border border-border py-3 focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary',
            'autocomplete':'off'
        })
    )
    
    username = forms.CharField(
        label="Email address",
        widget=forms.TextInput(attrs={
            'placeholder':'Enter email address',
            'class':'w-full rounded-md border border-border py-3 focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary',
            'autocomplete':'off'
        })
    )
    
    email = forms.EmailField(
        label="Email address",
        widget=forms.TextInput(attrs={
            'placeholder':'Enter email address',
            'class':'w-full rounded-md border border-border py-3 focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary',
            'autocomplete':'off'
        })
    )
    
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={
            'placeholder':'Enter password',
            'class':'w-full rounded-md border border-border py-3 focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary',
            'autocomplete':'off'
        })
    )
    
    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data.get("first_name")
        last_name = cleaned_data.get("last_name")
        username = cleaned_data.get("username")
        email = cleaned_data.get('email')
        password = cleaned_data.get("password")
        
        #check if username is already taken
        if User.objects.filter(username=username).exists():
            self.add_error('username','Username already taken')
            
        #check if email is already taken
        if User.objects.filter(email=email).exists():
            self.add_error("email","Email already taken")
        
        #password requirements
        uppercase_letters = "(?=.*?[A-Z])"
        lowercase_letters = "(?=.*?[a-z])"
        digits = "(?=.*?[0-9])"
        special_char = "(?=.*?[#?!@$%^&*-])"
        min_char = ".{8,}$"
        
        #check password pattern
        password_patterns = "^"+"".join([uppercase_letters,lowercase_letters,digits,special_char,min_char])      
        is_valid = re.match(password_patterns,password)
        if not is_valid:
            self.add_error("password","password should contain:[uppercase,lowercase,numbers,min 8 characters]")
        
        return cleaned_data
        
    

elearning/apps/accountapp/views.py
from django.shortcuts import redirect, render, HttpResponse
from django.contrib.auth import authenticate, get_user_model, login,logout
from .forms import*
from django.contrib import messages
# Create your views here.

def login_user(request):
    # check if the request is using form
    if request.method == "POST":
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            try:
                username = request.POST['username']
                password = request.POST['password']
                
                #check if the credentials are correct
                user = authenticate(request,username=username,password=password)
                if user is not None:
                    login(request,user) #session to login the current user
                    #redirect to home page
                else: messages.error(request,"Error: Invalid username or password") #session of message
                return redirect("accountapp:login_url") #back to login
            except Exception as e:
                messages.error(request,f"Error: {e}")
            
    else:
        login_form = LoginForm() #provide the forms.py
    
    template = "login.html"
    context = {
        "form": login_form
    }
    
    # check if the user already logged in
    if request.user.is_authenticated:
        #redirect to home page
        return HttpResponse('login')
    else:
        return render(request,template,context) #logged in

User = get_user_model()

def registration(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            try:
                #get data from the form
                username = form.cleaned_data.get('username')
                first_name = form.cleaned_data.get('first_name')
                last_name = form.cleaned_data.get('last_name')
                email = form.cleaned_data.get('email')
                password = form.cleaned_data.get('password')

                #add new user
                new_user = User.objects.create_user(
                    username=username,
                    email=email,
                    password=password,
                    first_name=first_name,
                    last_name=last_name,
                    is_instructor=False  # You can set this based on your logic
                )
                new_user.save()
                messages.success(request,message="New account created")
                return redirect('accountapp:login_url') #login page
            except Exception as e:
                messages.error(request,message=f"Error: {e}")
    else:
        form = RegistrationForm()

    template = "registration.html"
    context = {
        "form": form,
    }

    #check if already logged in
    if request.user.is_authenticated:
        #go to home page
        pass
    else:
        return render(request, template, context) #registration page

elearning/apps/accountapp/templates/login.html
{% extends 'base.html' %}
{% load static  %}
{% block title %}
login
{% endblock %}

{% block content %}
<section class=" h-full w-full flex items-center justify-center">
    <div class="flex items-center justify-center w-4/5 h-3/5 flex-col rounded-md shadow-lg shadow-border md:flex-row">
        <div class="w-full h-full hidden md:block">
            <img class="w-full h-full object-obtain rounded-l-md" src="{% static 'assets/login_vector.png' %}" alt=""/>
        </div>
        <div class="w-full flex-col p-5 gap-2 h-full">
            <p class="text-3xl font-bold text-secondary-0 text-center">Sign in</p>

            {% comment %} display messages {% endcomment %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{message.tags}}" {% endif %}>{{message}}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <form method="POST" action="{% url 'accountapp:login_url' %}" class="flex flex-col justify-center h-4/5 w-full">
                {% csrf_token %}

                <div class="flex flex-col gap-2">
                    {{ form.username.errors }}
                    <label class="text-gray-600" for="{{ form.username.id_for_label }}">Email address / Username</label>
                    {{ form.username }}
                </div>

                <div class="flex flex-col gap-2 mt-3">
                    <label class="text-gray-600" for="{{ form.password.id_for_label }}">Password</label>
                    {{ form.password }}
                </div>

                <button class="bg-primary hover:bg-[#78A582] font-medium text-white py-3 mt-5 rounded-md">Sign in</button>
               
                <p class="text-center mt-2">
                    <a href="{% url 'accountapp:register_url' %}">Doesn’t have an account? <span class="text-accent font-medium">Register here..</span></a>
                </p>
            </form>

        </div>
    </div>
</section>
{% endblock %}

elearning/apps/accountapp/templates/registration.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Regiter
{% endblock %}

{% block content %}
<section class=" h-full w-full flex items-center justify-center">
    <div class="flex items-center justify-center w-4/5 h-3/5 flex-col rounded-md shadow-lg shadow-border md:flex-row">
        <!-- logo -->
        <div class="w-full h-full hidden md:block">
            <img class="w-full h-full object-obtain rounded-l-md" src="{% static 'assets/login_vector.png' %}" alt=""/>
        </div>
        <!-- forms -->
        <div class="w-full flex-col px-5 gap-2 h-full rounded-md">
            <p class="text-lg md:text-3xl font-bold text-secondary-0 text-center mb-2">Register</p>
            <form method="POST" action="{% url 'accountapp:register_url' %}" class="flex flex-col gap-2 p-3 justify-center h-4/5 w-full">
                {% csrf_token %}
                <div class="flex gap-2 w-full">
                    <div class="flex flex-col w-1/2">
                        <label for="{{ form.first_name.id_for_label }}">First name</label>
                        {{form.first_name}}
                    </div>
                    <div class="flex flex-col w-1/2">
                        <label for="{{form.last_name.id_for_label}}">Last name</label>
                        {{form.last_name}}
                    </div>
                    
                </div>
                <div class="flex flex-col">
                    <div class="flex justify-between">
                        <label for="{{form.email.id_for_label}}">Username</label>
                        {{ form.username.errors }}
                    </div>
                    {{form.username}}
                </div>
                <div class="flex flex-col">
                    <div class="flex justify-between">
                        <label for="{{form.email.id_for_label}}">Email address</label>
                        {{ form.email.errors }}
                    </div>
                    {{form.email}}
                    
                </div>
                <div class="flex flex-col">
                    <label for="{{form.password.id_for_label}}">Password</label>
                    {{form.password}}
                    {{ form.password.errors }}
                </div>

                <button type="submit" class="w-full py-3 mt-2 bg-primary text-white rounded-md font-medium">Create account</button>
            </form>
            <a href="{% url 'accountapp:login_url' %}">
                <p class="text-center mt-2">Already have an account? <span class="font-bold text-primary">Login</span></p>
            </a>
        </div>
    </div>
</section>
{% endblock %}